name: Build & test (develop)

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'develop'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install coverage
      - run: pip install numpy>=1.19
      - run: python setup.py build_ext --inplace

      - name: Run tests with coverage
        run: |
          coverage run --source flowutils --omit="flowutils/tests/*" run_tests.py
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true

